repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-merge-conflict

- repo: local
  hooks:
    - id: terraform-fmt
      name: Terraform fmt
      entry: powershell -NoProfile -Command "terraform fmt -recursive"
      language: system
      pass_filenames: false
      files: \.(tf|tfvars)$

    - id: terraform-validate-staging
      name: Terraform validate staging
      entry: powershell -NoProfile -Command "Push-Location environments/staging; terraform init -backend=false; terraform validate; Pop-Location"
      language: system
      pass_filenames: false
      files: \.(tf|tfvars)$

    - id: terraform-validate-production
      name: Terraform validate production
      entry: powershell -NoProfile -Command "Push-Location environments/production; terraform init -backend=false; terraform validate; Pop-Location"
      language: system
      pass_filenames: false
      files: \.(tf|tfvars)$
