repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_tflint
    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color
    - id: terraform_tfsec

- repo: https://github.com/bridgecrewio/checkov.git
  rev: 2.5.9
  hooks:
    - id: checkov
      verbose: true
      args: [--quiet]
